---
- hosts: all
  become: yes
  tasks:
    - name: Ensure Apache is installed
      package:
        name: apache2
        state: present
    - name: Enable Apache2 service
      command: systemctl enable apache2
    - name: Restart Apache2 service
      command: systemctl restart apache2
